; Configuração do ESP32 de Ambiente
[env:ambiente]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
; Compila apenas a pasta ambiente e a pasta shared
build_src_filter = +<esp32-ambiente/ambiente/> +<shared/>
lib_deps = 
	adafruit/DHT sensor library@^1.4.7
	knolleary/PubSubClient@^2.8

; Configuração do ESP32 de Segurança
[env:seguranca]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
; Compila apenas a pasta seguranca e a pasta shared
build_src_filter = +<esp32-seguranca/seguranca/> +<shared/>
lib_deps = 
	knolleary/PubSubClient@^2.8